#!/bin/sh

set -o nounset

file=$1

cp $file .
file=`basename $file`

echo Unpacking asterix distribution...
sed -i "s/ADD .* \/asterix\//ADD $file \/asterix\//" Dockerfile
docker rmi -f jianfeng/asterixdb 
docker build --rm -t jianfeng/asterixdb .

[ "$1" == "$file" ] || { \rm -f $file ;}

